apiVersion: batch/v1
kind: Job
metadata:
  name: copyexplorerconfig
  labels:
    app: copyexplorerconfig
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copyexplorerconfig
    spec:
      restartPolicy: "Never"
      volumes:
      - name: explorer-crypto-config-pvc
        persistentVolumeClaim:
          claimName: explorer-crypto-config-pvc
      - name: explorer-config-pvc
        persistentVolumeClaim:
          claimName: explorer-config-pvc
      - name: explorer-database-pvc
        persistentVolumeClaim:
          claimName: explorer-database-pvc
      containers:
      - name: copy-explorer-config
        image: alpine:3.7
        imagePullPolicy: Always
        command: ["sh", "-c", "while [ ! -f /tmp/copy_explorer_config_done ]; do echo Waiting for artifacts to be copied; sleep 1; done;"]
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/
          name: explorer-database-pvc
        - mountPath: /explorer
          name: explorer-config-pvc
        - mountPath: /tmp/crypto/
          name: explorer-crypto-config-pvc