apiVersion: batch/v1
kind: Job
metadata:
  name: copyartifacts
  labels:
    app: copyartifacts
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copyartifacts
    spec:
      restartPolicy: "Never"
      volumes:
      - name: artifacts
        persistentVolumeClaim:
          claimName: artifacts-pvc
      - name: buildpack
        persistentVolumeClaim:
          claimName: chaincode-buildpack-pvc
      - name: peer-config
        persistentVolumeClaim:
          claimName: peer-config-pvc
      containers:
      - name: copy-hlf-artifacts
        image: alpine:3.7
        imagePullPolicy: Always
        command: ["sh", "-c", "while [ ! -f /shared/copy_artifacts_done ]; do echo Waiting for artifacts to be copied; sleep 1; done;"]
        volumeMounts:
        - mountPath: /shared
          name: artifacts
        - mountPath: /opt/buildpack/bin
          name: buildpack
        - mountPath: /etc/hyperledger/fabric/
          name: peer-config