kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: explorer-crypto-config-pvc
  labels:
    app: blockchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi