apiVersion: apps/v1
kind: Deployment
metadata:
  name: "peer0-org{NUMBER}"
  labels: 
    component: "peer0-org{NUMBER}"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "peer0-org{NUMBER}"
  template:
    metadata:
      labels:
        component: "peer0-org{NUMBER}"
    spec:
      volumes:
      - name: artifacts
        persistentVolumeClaim:
          claimName: artifacts-pvc
      - name: chaincode-buildpack
        persistentVolumeClaim:
          claimName: chaincode-buildpack-pvc
      - name: peer-config
        persistentVolumeClaim:
          claimName: peer-config-pvc
      containers:
      - name: peer0-org{NUMBER}
        image: hyperledger/fabric-peer:2.3.0
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        env:
        - name: FABRIC_LOGGING_SPEC
          value: debug:cauthdsl,policies,msp,grpc,peer.gossip.mcs,gossip,leveldbhelper=info
        - name: CORE_PEER_ID
          value: peer0-org{NUMBER}
        - name: CORE_PEER_ADDRESS
          value: peer0-org{NUMBER}:7051
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer0-org{NUMBER}:7051
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: peer0-org{NUMBER}:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0-org{NUMBER}:7051           
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_LOCALMSPID
          value: Org{NUMBER}MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org{NUMBER}.example.com/peers/peer0.org{NUMBER}.example.com/msp/
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: //shared/crypto-config/peerOrganizations/org{NUMBER}.example.com/peers/peer0.org{NUMBER}.example.com/tls/ca.crt
        - name: CORE_PEER_TLS_CERT_FILE
          value: /shared/crypto-config/peerOrganizations/org{NUMBER}.example.com/peers/peer0.org{NUMBER}.example.com/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /shared/crypto-config/peerOrganizations/org{NUMBER}.example.com/peers/peer0.org{NUMBER}.example.com/tls/server.key
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: goleveldb
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer:7050
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - name: artifacts
          mountPath: /shared
        - name: chaincode-buildpack
          mountPath: /opt/buildpack/bin
        - name: peer-config
          mountPath: /etc/hyperledger/fabric
        ports:
          - containerPort: 7051
          - containerPort: 7052
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-org{NUMBER}
  labels:
    run: peer0-org{NUMBER}
spec:
  type: ClusterIP
  selector:
    component: "peer0-org{NUMBER}"
  ports:
  - name: "grpcs"
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: "chaincode-listen-address"
    port: 7052
    protocol: TCP
    targetPort: 7052